### ISSUE TITLE
🎫 Falta un endpoint de count

### ISSUE THREAD

**Issue by Marcopole11** [aaronmbdev/missioworship-backend#16]
Para las consultas con paginación, el cliente necesita poder saber cuántas páginas puede mostrar.
Tanto si hacemos la paginación a mano como si [usamos un componente de paginación ya hecho](https://ng-bootstrap.github.io/#/components/pagination/examples).

Por lo tanto todo servicio que tenga un endpoint con paginación tiene que tener también un endpoint "count" que bajo los mismos filtros (escepto los de paginación) devuelva el total de resultados.

Por poner un ejemplo, si en el endpoint se pueden filtrar los usuarios por los que empiezan por M, que count me pueda decir el total de usuarios que empiezan por M.

**Comment by aaronmbdev** [comment]
Por el momento no tenemos filtros para el listado de usuarios pero para canciones sí que tendremos. Voy a añadir el campo total_results en la respuesta paginada para que sepas cuántos elementos tienes en total.
